### ISSUE TITLE
主页-日历区域

### ISSUE THREAD

**Issue by lvzhegeyi** [LinMoQC/Memory-Blog#1]
显示19月，且没有翻页方式
![屏幕截图 2024-02-02 194217](https://github.com/LinMoQC/LinMoBlog/assets/104721825/d3f36e6f-7c13-43cc-bccb-2ab174c4c3c8)

**Comment by LinMoQC** [comment]
![image](https://github.com/LinMoQC/LinMoBlog/assets/59323207/9933cbda-500c-4155-8fed-f24ea5b3d3fe)
已禁用日期选择，修复了日期显示
