### ISSUE TITLE
UI的小提议

### ISSUE THREAD

**Issue by LangYa466** [LinMoQC/Memory-Blog#18]
>暗黑模式
![3d114351cc1d940aa4864e0c0f6b5e00](https://github.com/LinMoQC/Memory-Blog/assets/140164829/639d16f3-e9f5-4dd9-ae27-9c292438bc24)
觉得这里的文字显示的颜色还是改成浅色调比较好qwq

**Comment by LinMoQC** [comment]
> >暗黑模式
> ![3d114351cc1d940aa4864e0c0f6b5e00](https://github.com/LinMoQC/Memory-Blog/assets/140164829/639d16f3-e9f5-4dd9-ae27-9c292438bc24)
> 觉得这里的文字显示的颜色还是改成浅色调比较好qwq
> 

这个是之前留下来的问题，忘记改了，后面会统一的
