### ISSUE TITLE
主页-头像简介部分

### ISSUE THREAD

**Issue by lvzhegeyi** [LinMoQC/Memory-Blog#2]
光标闪烁位置不合理，且光标跟字只有一行的动作，在展示第二行的时候光标没有跟上
![屏幕截图 2024-02-02 194324](https://github.com/LinMoQC/LinMoBlog/assets/104721825/2ca3a585-e755-4186-9b1c-b8ea1d6b8496)
![屏幕截图 2024-02-02 195200](https://github.com/LinMoQC/LinMoBlog/assets/104721825/b8186422-1d0f-4e86-a29f-33258b0bb0dc)

**Comment by LinMoQC** [comment]
光标关了，转行好像无法解决
