### ISSUE TITLE
笔记-导航

### ISSUE THREAD

**Issue by lvzhegeyi** [LinMoQC/Memory-Blog#5]
在切换黑夜模式后导航字体没有变色
![屏幕截图 2024-02-02 200833](https://github.com/LinMoQC/LinMoBlog/assets/104721825/9afe0114-228b-4cc5-89ed-d640dfe6f791)

**Comment by lvzhegeyi** [comment]
此处的小房子（主页）链接指向似乎有些问题，其链接为（/LinMoBlog/），应为（/LinMoBlog/#/dashboard）
![屏幕截图 2024-02-02 201454](https://github.com/LinMoQC/LinMoBlog/assets/104721825/aa1fb5ba-6e0a-466d-b59d-6aece107dba2)

**Comment by LinMoQC** [comment]
![image](https://github.com/LinMoQC/LinMoBlog/assets/59323207/1af3b6c7-70be-4d03-b6c0-a37a0ce0a623)
![image](https://github.com/LinMoQC/LinMoBlog/assets/59323207/a1b13905-f7a3-4420-809d-4908b17aa625)
已修复
